### ISSUE TITLE
Export Select Output Dialog Dark Theme Visibility Issues

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#370] opened 2017-05-29 21:43 UTC
Part of the functionality of the Coordinate Conversion pane is the ability to export. After you click export, you get the Select Output dialog.  

-[ ] Select Output dialog has white text on a white back ground, so you cannot tell which option you have selected with the radio button.
![image](https://cloud.githubusercontent.com/assets/5322669/26562970/3f3a6fe6-4480-11e7-962a-fb39114f8a48.png)
(currently looks like this)

**Comment by dfoll** [comment] 2017-05-29 22:10
While some one is messing with this dialog there is one other issue with this dialog, however i would say it's "time permitting" and you would decide how much time it will take, as #369  is a bigger deal. If taking the time to fix the overall look of the dialog is too risky, it can be added to (insert issue).

- [ ] Select Output dialog does not match dark theme dialogs from core. Dark theme dialogs use a dark background, Select Fields does not.
![image](https://cloud.githubusercontent.com/assets/5322669/26563031/f1801764-4480-11e7-9855-63d54fd64294.png)

**Comment by csmoore** [comment] 2017-05-30 18:20
Also addressed in #372 - should look like this after merge:

![image](https://cloud.githubusercontent.com/assets/3090809/26598386/0ee8aa24-4543-11e7-8c72-94e723697177.png)

**Comment by NatalieCampos** [comment] 2017-05-30 20:25
@csmoore that is exactly how the dialog looks.... however I am unable to export the points due to the error below... i am gonna continue testing to try to get the reproduction steps and I will make another issue...

![image](https://cloud.githubusercontent.com/assets/5116835/26603370/7b643fa4-453b-11e7-9fa0-2978ec6425a1.png)

**Closed by NatalieCampos** 2017-05-30 20:25 UTC
Labels: 3 - Verify, B - Bug
