### ISSUE TITLE
Coordinate Conversion does not provide an output MGRS/USNG coordinate in the polar regions (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#262] opened 2017-01-12 23:59 UTC
Outside of 80 degree South and 84 degree North, MGRS is defined in terms of Universal Polar Sterographic (UPS). So for example, if you use the Identify tool in ArcMap at 87.7520N 169.6139E, it will switch to using UPS and return the MGRS and USNG value ZAK4500045522, which is the same value that Geotrans will return.

Currently when you paste in the value 87.7520N 169.6139E it will not return an MGRS or USNG value.

My guess is this was never specified as a design/implementation requirement for Coordinate Conversion; may have to wait until a future release.

**Comment by NatalieCampos** [comment] 2017-09-07 17:30
When @elinz coordinates example are put into ArcMap, no point is dropped and the cursor zooms off the basemap into white space.

When the same coordinates are put into Pro 1.4, the invalid coordinate dialog is given.

**Comment by lfunkhouser** [comment] 2019-09-13 13:13
duplicate of #341

**Closed by lfunkhouser** 2019-09-13 13:13 UTC
Labels: A-bug, E-duplicate, T-ArcGIS Pro, T-ArcMap
