### ISSUE TITLE
BUG-000104918  ArcGIS Pro crashes when opening existing projects if the Military Tools Coordinate Conversion tool pane is docked.

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/coordinate-conversion-addin-dotnet#353] opened 2017-05-19 20:02 UTC
<div><div>
<span><b>Salesforce ID:</b> BUG-000104918</span><br/>
<span><b>Salesforce Submitter:</b> Shondra Grenz</span><br/>
<span><b>Salesforce Submit Date:</b> 5/04/2017 1:25 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Crash</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000104918</span><br/>
<span><b>Work Around:</b> To prevent crashing, open a new project and close the Coordinate Conversion tool so that it is no longer docked in the ArcGIS Pro template pane. Close ArcGIS Pro and reopen the project and it should not crash. Then, open the Coordinate Conversion tool to use it as needed.

Main thing is to not have the Coordinate Conversion tool docked in the ArcGIS Pro Template when opening the project, but rather open it to use and close it when done.</span><br/>
<span><b>Product:</b> ArcGIS Pro</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 1.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by kgonzago** [comment] 2017-05-25 14:37
I cannot reproduce this bug on Pro 1.4.1 using MT build 1508 (current). Having another set of eyes for testing is needed.

FYI @topowright @NatalieCampos @dfoll @ACueva

**Comment by NatalieCampos** [comment] 2017-05-25 18:33
@nfeuerstein @lfunkhouser unable to reproduce this on the1508 build. Shall we close it?

**Comment by nfeuerstein** [comment] 2017-05-25 18:38
If it can't be reproduced, works for me. Let's close it.

**Closed** 2017-05-25 20:54 UTC
Labels: 4 - Done, B - Bug, support
