### ISSUE TITLE
Manually inputed text to list does not function properly

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#461] opened 2017-12-15 04:32 UTC
Currently if you enter coordinates manually they do not add to the list. As a user anything that I enter into the input box should add to the list box. 

Steps to replicate: 
Copy coordinate into the input box- 36RUU1898318280

Nothing will add to the map or the list

**Comment by csmoore** [comment] 2017-12-15 16:41
Is this different from #457 - (except for the bug reported in #460 with the test addin) ?

**Comment by lfunkhouser** [comment] 2017-12-20 00:36
Closing. Duplicate of #457

**Closed by lfunkhouser** 2017-12-20 00:36 UTC
Labels: A-bug, E-duplicate
