### ISSUE TITLE
Coordinate Conversion is auto correcting invalid input coordinates (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#255] opened 2017-01-12 02:43 UTC
Enter the following invalid coordinate: 45 300s|100 30.0w

The tool auto corrects the 300s to 5 minutes and creates the following output:
![image](https://cloud.githubusercontent.com/assets/4635490/21874896/d27a6024-d82c-11e6-8be4-cedfd63dc535.png)

The tool should not auto correct invalid coordinates. The tool should interpret this as invalid and clear the output coordinate textboxes as an indicator to the user that the input is invalid so the user can verify the input coordinate.

**Comment by nfeuerstein** [comment] 2017-01-12 17:20
Document that we convert incorrect coordinates by computing - give example.  80 seconds becomes 1 minute 20 seconds, etc.

Future: Validate via regular expression and tell the user that the coordinate was invalid.

Note from Joe McCausland - having to press enter with manual input should resolve this.

**Comment by jmccausland** [comment] 2017-01-12 17:37
Will need to catch these prior to sending to arcobjects if arcobjects is indeed "auto-correcting" these

**Comment by dfoll** [comment] 2017-01-14 20:48
noted this in the most recent version of the pdf in the supported notation section near the top as the last bullet under degree based formats. @topowright and @NatalieCampos  agreed it satisfied the "affects documentation" tag... removing "affects "documentation" leaving the issue itself open with the bug tag in case this is something we want to fix

**Comment by dfoll** [comment] 2017-01-14 20:52
the pub on blaster will have these changes if anyone wants to verify the removal of the affects documentation tag, they won't be picked up by jenkins until another build kicks off

**Comment by dfoll** [comment] 2017-01-14 21:51
This has been added as a note in the documentation; however, it is not in the known issues list.

**Comment by dfoll** [comment] 2017-01-14 21:52
This has been added to the documentation; however, it is not in the known issue list.

**Comment by NatalieCampos** [comment] 2017-09-07 19:22
@elinz unable to reproduce on the most current release of CC single addin.  I pasted (45 300s|100 30.0w) into the Input coordinate box.  And I get the Invalid Coordinate box dialog.  Does getting the Invalid Coordinate dialog solve the original issue of auto correcting invalid coordinates?  If so please close the issue.

**Comment by elinz** [comment] 2017-09-07 20:26
@NatalieCampos I would test other invalid coordinate values. The particular value that I used had an invalid minute value. You should test other invalid coordinate components as well. For example, test invalid lat and longitude degree value, lat and longitude minute value, and lat and long seconds value. We need to make sure that there are unit tests created with this invalid values to make sure they throw the invalid error.

**Comment by dfoll** [comment] 2018-06-24 17:30
I do not see this as an issue with 10.6.1 MT build 48
also tried
35 180 52.14N 098 47 32.15W
35 180 52.14N 098 47 302.15W
 properly bounced back Invalid Coordinate window

**Comment by topowright** [comment] 2018-08-06 18:49
This has been addressed in previous release MT 3.0

**Closed by topowright** 2018-08-06 18:49 UTC
Labels: A-bug, E-verified, V -  Pro 2.1, V - 10.3.1
