### ISSUE TITLE
UTM coordinates always off by 1

### ISSUE THREAD

**Issue by ACueva** [Esri/coordinate-conversion-addin-dotnet#141] opened 2016-11-04 15:40 UTC
_From @ACueva on November 3, 2016 15:55_

Not sure if this a bug or not.
Whatever value that's entered UTM will always be off by 1.

![coordinateconversion_screencapturedtandpro](https://cloud.githubusercontent.com/assets/3093940/19973625/fbc05832-a1a2-11e6-8914-be610f2766b5.PNG)

In addition, when expected outputs are checked against
http://egeoint.nrlssc.navy.mil/web_geographic_translator/faces/tabbed_transform.jsp
it is also off by 1.

_Copied from original issue: Esri/distance-direction-addin-dotnet#169_

**Comment by ACueva** [comment] 2016-11-04 15:40
_From @jmccausland on November 4, 2016 14:52_

@ACueva This should be added to the CC repo.  What version of ArcMap and Pro are you running?  I can't reproduce this issue with your test data at 10.5 Desktop or Pro 1.3.1.  In addition I've tested both the released and Dev version.

**Comment by ACueva** [comment] 2016-11-04 15:40
@jmccausland Good call, i'll move this to the right Repo.  If you look at the image above you can see what i'm referring to.  MGRS. USNG both end in 90.  UTM ends with 89.  If we plug that same value into http://egeoint.nrlssc.navy.mil/web_geographic_translator/faces/tabbed_transform.jsp UTM ends in 90.

**Comment by jmccausland** [comment] 2016-11-04 15:47
I looked at you image and can't reproduce the stated issue.

**Comment by ACueva** [comment] 2016-11-04 16:18
I looked at the exact values, for some reason now, it's off by one at the 87
Input:10SFF5288833490

USNG:10SFF5288833490
UTM: 10N 652887 4033490

**Comment by jmccausland** [comment] 2016-11-04 17:15
What are the results at Desktop 10.3.1?  10.4?  10.5?  I'm asking this because the output uses the IConversionNotation interface and there may be different results due to rounding policies.  Basically this will most likely be a core issue.

**Comment by topowright** [comment] 2017-01-13 22:44
@jmccausland I am able to replicate this issue when I convert from MRGS to MGRS in ArcGIS Pro and ArcMap. The example I have is for the location 51.5 0. This is off by less than 5 ft.

**Comment by dfoll** [comment] 2017-01-14 22:42
This has been addressed in issue number: #252

**Closed** 2017-01-14 22:44 UTC
Labels: B - Bug, B - Can't Reproduce
