### ISSUE TITLE
Coordinate Conversion generating output for input values that are ambiguous (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#208] opened 2017-01-04 00:07 UTC
The addin is generating output for input values that are ambiguous.

Some examples, below:

- [ ] Input value: 00
![image](https://cloud.githubusercontent.com/assets/4635490/21627667/3c9de6a2-d1ce-11e6-9366-f778c92d1133.png)
This doesn't become a valid value until 00 is separated by a space, a comma or one of the other valid coord-pair-separators (http://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm)

- [ ] Input value: 45
![image](https://cloud.githubusercontent.com/assets/4635490/21627710/9727c228-d1ce-11e6-9c46-339189dcf01c.png)

- [ ] Input value: 457898
![image](https://cloud.githubusercontent.com/assets/4635490/21627654/277a9e6e-d1ce-11e6-907f-1800299a0b4c.png)

@topowright FYI.

**Comment by dfoll** [comment] 2017-01-14 22:23
This is what we will add to the known issues list in the documentation.

When entering integers without spaces the coordinates will be returned as inaccurate. As an example:

12 returns 1N 2E
 1234 returns 4N 123E

**Comment by adgiles** [comment] 2017-02-07 11:13
@dhagens 

This update seems to have caused an issue with the Add New Output Coordinate window if the map point tool is active.

To reproduce click on the Map Tool Button and whilst the tool is in active mode (coordinates updating as you move the mouse), click the add new output button.

Instead of getting the Add New Output Coordinate window you now get the Ambiguous Coordinate window clicking ok 3 times eventually gets the correct window open, hitting the close cross causes Pro to crash

**Comment by dhagens** [comment] 2017-02-07 14:19
@adgiles, @kgonzago - I got the latest from CC and I'm not seeing the issues that you are seeing.  We don't have an 'add new output' button.  We have an 'Edit Properties' button and an 'Add' button.  I'm not sure which one you are referring to.  Either way, I tested both buttons several times and all seems to be functioning properly for me.

**Comment by lfunkhouser** [comment] 2017-04-28 12:26
Assigning to MT PEs and @elinz who originally submitted the issue to verify. Release notes for next release will need to be updated too if this is fixed.

**Comment by NatalieCampos** [comment] 2017-04-28 21:57
Per @topowright, this issue has not been fixed.  When inputting @elinz 's coordinate examples, I do not receive the ambiguous input dialog.

**Comment by lfunkhouser** [comment] 2017-05-01 19:56
Assigning back to Devs - @kgonzago @pHill5136 @csmoore

**Comment by kgonzago** [comment] 2017-05-01 22:18
@lfunkhouser I'll take this one.

**Comment by topowright** [comment] 2017-05-02 19:07
The expected behavior would be when a user puts in a coordinate that is not clear that the tool will prompt them to allow the tool to understand what they mean. 

If a user puts in 11 or 1234 or 123456 as examples the feedback should be: 
![image](https://cloud.githubusercontent.com/assets/5488313/25634470/a1b9b5d4-2f2f-11e7-90ba-cd9d4f3688f1.png)

Currently this prompt happens correctly if there is a space in the inputs as an example 1 1, 12 34 , 123 456

**Comment by csmoore** [comment] 2017-05-03 21:19
@kgonzago 's PR merged - ready for retest in next build

**Comment by ACueva** [comment] 2017-05-03 21:20
Kicking off a new build right now. Should be ready in a few mins.

**Comment by NatalieCampos** [comment] 2017-05-03 22:45
None of Erics examples throw an ambigous error.... That is what I think is supposed to happen @topowright  @csmoore  @lfunkhouser

**Comment by NatalieCampos** [comment] 2017-05-03 22:46
This was tried wit the 1428 build

**Comment by kgonzago** [comment] 2017-05-04 13:14
@NatalieCampos The new behavior should display a message informing users of an invalid coordinate. The ambiguous message will not be thrown until a valid coordinate is entered. Do you not see the invalid coordinate message during your testing?

**Comment by kgonzago** [comment] 2017-05-04 14:44
@NatalieCampos I was able to repro from build 1428. Applied fix and you will be able to test once PR #326  is merged and build kicked off.

**Comment by kgonzago** [comment] 2017-05-04 14:55
@NatalieCampos @ACueva @topowright FYI

**Comment by ACueva** [comment] 2017-05-04 15:15
I kicked off a manual build.  It should be ready to test by the time you see this message.

**Comment by NatalieCampos** [comment] 2017-05-04 16:05
This was tested on this morning's build.  I now get the error box below. Closing this issue.

![image](https://cloud.githubusercontent.com/assets/5116835/25713201/c5a97702-30a8-11e7-8447-06cd03015428.png)

**Closed by NatalieCampos** 2017-05-04 16:05 UTC
Labels: B - Bug, P - Coordinate Conversion, V - Pro 1.4
