### ISSUE TITLE
Pro crashes when clicking "Add" button on Coordinate Conversion pane after searching for location

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#424] opened 2017-08-11 15:27 UTC
Copy/paste this coordinate into the Coordinate Conversion input box:
39.0392N, 125.7625E
Hit Enter.
I'm zoomed to this location, I see it flash on screen.
Hit Add button.
Pro crashes.
![image](https://user-images.githubusercontent.com/3801392/29220074-feb6d68e-7e87-11e7-84b8-1d75e066066a.png)

ArcGIS Pro 2.0
Military Tools Add-In 2.0 version
(ArcGIS Pro 2.0, add-in downloaded from Solutions page, version for Pro 2.0 - add-in installer 6/28/2017)

**Comment by NatalieCampos** [comment] 2017-09-07 18:46
Test this on 9/7/ unable to reproduce this bug.  Closing Issue.

**Closed by NatalieCampos** 2017-09-07 18:46 UTC
Labels: B - Bug, G - Defense Team, V - Pro 2.0
