### ISSUE TITLE
Coordinate Conversion expects components of latitude and longitude input values to be balanced (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#246] opened 2017-01-11 04:10 UTC
### DDM example:
If a enter a decimal minute component for latitude, the addin expects the longitude to also have a decimal minute component.

- Type in the following coordinate: 45 0.0N 100 0.0W
The input is interpreted and output coordinates are displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21835021/92de09e8-d76e-11e6-92ea-9819dc2b4176.png)

- Now edit 100 0.0W in the input textbox to be 100 0W by backspacing.
The input is still interpreted and output coordinates are displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21835061/e94efaa8-d76e-11e6-8783-ef0f53c86363.png)

- Now edit 100 0W in the input textbox to be 100W by backspacing.
The input is no longer interpreted even through the values 45 0.0N 100 0.0W and 45 0.0N 100W are equivalent:
![image](https://cloud.githubusercontent.com/assets/4635490/21835079/12ce0cb6-d76f-11e6-9b42-3d6b1029da9d.png)

### DMS example:
If a enter a seconds component for latitude, the addin expects the longitude to also have a seconds component.

- Type in the following coordinate: 45 0 0.0N 100 0 0.0W
The input is interpreted and output coordinates are displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21835143/8a8987e4-d76f-11e6-99fc-b37e3d1ca90e.png)

- Now edit 100 0 0.0W in the input textbox to be 100 0W by backspacing.
The input is not longer interpreted even through the values 45 0 0.0N 100 0 0.0W and 45 0 0.0N 100 0W are equivalent:
![image](https://cloud.githubusercontent.com/assets/4635490/21835178/d4bc102a-d76f-11e6-892e-0de0d4d3fca1.png)

**Comment by elinz** [comment] 2017-01-11 18:29
@nfeuerstein We will add a note to the doc about this limitation.

**Comment by dfoll** [comment] 2017-01-12 18:27
@Dbarnes1

**Comment by dfoll** [comment] 2017-01-14 18:30
@NatalieCampos can you please look at the documentation for this, (in the supported formats section) and see if you think this is sufficiently documented. if you feel it is, please remove the "affects documentation" tag, if not, we need to discuss what additionally needs written

**Comment by dfoll** [comment] 2017-01-14 18:50
the four of us @NatalieCampos @topowright @lfunkhouser have reviewed what exists in the documentation, we believe that what is there satisfies the "affects documentation" tag, removing the "affects documentation" tag

**Comment by dfoll** [comment] 2018-06-24 17:11
I do not believe this is an issue in ArcMap any longer with MT 3.0 build 48

**Comment by lfunkhouser** [comment] 2019-09-13 13:41
Closing. Duplicate of #245

**Closed by lfunkhouser** 2019-09-13 13:41 UTC
Labels: A-bug
