### ISSUE TITLE
Display problem when viewed after "auto hide"

### ISSUE THREAD

**Issue by ChristianDiscer** [Esri/coordinate-conversion-addin-dotnet#140] opened 2016-11-02 17:27 UTC
ArcMap for Desktop 10.3.1.4959
Coordinate Conversion (CC) 9/23/2015 Ver 1.0

1. Activate the CC add-in
2. Click the "auto hide" pin to collapse the CC window
3. Click the collapsed CC tab to redisplay the window - The window display's like this.

![screenshot](https://cloud.githubusercontent.com/assets/23219381/19939054/58c5ec4e-a0f5-11e6-8ec8-af89fb61a618.jpg)

4. Clicking the "auto hide" pin again (forcing it to be open) refreshes the CC window and correctly displays the CC window.

Notes:
- Other collapsable windows do not have display problems
- It does not matter where the CC window is docked - left or right side of ArcMap

**Comment by jmccausland** [comment] 2016-11-02 18:49
I'm unable to reproduce this at Desktop 10.5 with the version you're using or the current github source.  Maybe someone, @mfunk @nfeuerstein, is still on 10.3.1 who can test with your steps.

**Comment by ChristianDiscer** [comment] 2016-11-02 19:41
In case this information is also important...

OS: Windows 7 Pro SP1 64-bit
Display adapter: AMD Radeon R9 270

![screenshot](https://cloud.githubusercontent.com/assets/23219381/19944239/fb540618-a108-11e6-9ea0-4c4365067d7f.jpg)

Need anything else?

**Comment by nfeuerstein** [comment] 2016-12-22 17:45
@elinz or @Dbarnes1 can you reproduce this issue?  If not, please close as not reproducible.

**Comment by elinz** [comment] 2016-12-22 18:10
@nfeuerstein @Dbarnes1 I'm creating a Windows 7 VM right now to test; only have access to Windows 7 Enterprise 64 bit, so won't be able to match OS exactly or the video card.

**Comment by elinz** [comment] 2016-12-28 19:02
@ChristianDiscer @nfeuerstein @Dbarnes1 I've installed the 1.0 build of this addin on a Windows 7 Enterprise 64 bit, and a Windows 8.1 Enterprise 64 bit machine (don't have access to Windows 7 Pro as the user does) running ArcMap 10.3.1 and I can't reproduce this issue. Closing this issue as not reproducible.

**Closed by elinz** 2016-12-28 19:02 UTC
Labels: 0 - Backlog, B - Bug, B - Can't Reproduce, priority - low
