### ISSUE TITLE
When inputting a coordinate out of the map view ArcMap Crashes

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#269] opened 2017-01-13 23:22 UTC
If you are in a projected coordinate system and you input a location that is outside of that projection ArcMap crashes.

**Comment by topowright** [comment] 2017-01-14 19:52
On my system this crashed. On @Dbarnes1 system the tool did not convert or flash the outputs.

**Comment by Dbarnes1** [comment] 2017-01-18 18:39
@topowright and I were unable to reproduce this issue today, closing out.

**Closed** 2017-01-18 18:39 UTC
Labels: B - Bug, B - Known Issue, P - Coordinate Conversion
