### ISSUE TITLE
Opening saved MXD with CC stand-alone add-in installed and CC open causes crash 

### ISSUE THREAD

**Issue by BobBooth** [Esri/coordinate-conversion-addin-dotnet#427] opened 2017-09-26 18:31 UTC
Install the stand-alone Coordinate Conversion add-in on ArcGIS 10.6 (build 8184).
Open the add-in in ArcMap, so the Coordinate Conversion window is open.
Save the map as a MXD.
Close ArcMap.
Open the MXD by double-clicking it.
ArcMap crashes.
![image](https://user-images.githubusercontent.com/3801392/30877233-1766d1ee-a2c7-11e7-835f-b7c8e4445bc6.png)
Open ArcMap to a new blank map.
ArcMap opens fine.
Open ArcMap and then browse to the map that crashed in the Recent list.
ArcMap opens the map fine.

(V - 10.6)

**Comment by BobBooth** [comment] 2017-09-26 18:34
Oops. Looks like this is a duplicate of
https://github.com/ArcGIS/solutions-defense/issues/424

**Comment by BobBooth** [comment] 2017-09-27 15:07
Also, for what it is worth, it is the Coordinate Conversion part that seems to be causing the crash. I can open maps with the Distance and Direction stand alone add-in installed and the window open just fine, but the same map, if I open CC will crash next time I open it.

**Comment by lfunkhouser** [comment] 2017-11-13 21:32
Closing. Duplicate of #424

**Comment by csmoore** [comment] 2017-12-05 18:03
This is still an issue - was requested by @lfunkhouser & @topowright  to re-open and link to https://github.com/Esri/military-tools-desktop-addins/issues/33

**Comment by csmoore** [comment] 2017-12-05 20:54
This should be ready to verify from: 

`Development\Commercial\DefenseSolutions\12-05-2017_1646\ArcMap\Addins\CoordinateConversion'
`Development`

`Development\Commercial\MilitaryToolsForArcGIS\12-05-2017_1646\ArcMap\Addins`

Note: this is an ArcMap-only issue that seems to occur most often on more recent versions (10.5+)

**Comment by csmoore** [comment] 2017-12-06 23:59
Updated version now at: `Development\Commercial\MilitaryToolsForArcGIS\12-06-2017_1649`

**Comment by BobBooth** [comment] 2017-12-07 17:01
Tested with 12-06-2017_1649 and ArcMap 10.6 (8319) - not seeing the crash on startup.
@csmoore

**Comment by topowright** [comment] 2017-12-12 02:24
Testing this on 8315 and not seeing an issue.

**Closed** 2017-12-12 02:55 UTC
Labels: A-bug, B - Showstopper, G-Development, V - 10.4.1, V - 10.5
