### ISSUE TITLE
ArcMap crash when using the Coordinate Conversion tool (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/coordinate-conversion-addin-dotnet#290] opened 2017-01-18 22:11 UTC
I was testing the fix for #285 when ArcMap crashed. I haven't been able to replicate what steps caused it to crash, but I think it's some combination of using the Map Point tool and change the Display Coordinates units.

**Comment by nfeuerstein** [comment] 2017-01-18 22:27
We need to be able to replicate the steps and crash it semi-consistently to know how to fix it.  Removing showstopper until/if it can be replicated.

**Comment by dhagens** [comment] 2017-02-06 16:05
@elinz, ready for testing once the merge is completed.

**Comment by lfunkhouser** [comment] 2017-05-01 19:57
Assigned to MT PEs to verify. @ACueva @dfoll @topowright @NatalieCampos

**Comment by NatalieCampos** [comment] 2017-05-02 23:05
Unable to reproduce this issue.  Closing it for now.

**Closed by NatalieCampos** 2017-05-02 23:05 UTC
Labels: 3 - Verify, B - Bug, P - Coordinate Conversion, V - 10.3.1

**Comment by topowright** [comment] 2017-05-04 17:19
We think that this issue might have been fixed when we addressed issue #319
