### ISSUE TITLE
Coordinate Conversion: After entering coordinates and hitting return, Pro does not "flash" the coordinate location on the map

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#155] opened 2016-12-14 22:12 UTC
_From @elinz on December 8, 2016 16:3_

In the ArcMap addin, when you enter coordinates and hit return, a crosshair(?) is flashed on the map display to show you where the entered coordinate is. If the coordinate location is not located in the current extent, the addin pans and centers the coordinate in the map. The ArcGIS Pro addin does none of this.

This is an import function to have, as it helps the user verify that they have entered the expected coordinate.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#77_

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @kgonzago on December 9, 2016 13:56_

@elinz Which version of Pro were you testing with?

fyi @lfunkhouser

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @kgonzago on December 9, 2016 14:35_

@jmccausland verified bug exists in Pro 1.3 and fix will be applied.

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @kgonzago on December 9, 2016 15:2_

@elinz Can you verify fix on Pro 1.3 when you have a moment?

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @elinz on December 9, 2016 16:15_

@kgonzago I build manually fire off Jenkins build and test.

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @elinz on December 9, 2016 17:36_

@kgonzago @jmccausland I tested and now the cross hairs are displayed, however, there are a couple of issues:
1. When I enter in a coordinate pair and hit return in order for the location to be flashed on the map, the Map Point Tool is enabled, so if I happen to place the mouse over the map I now lose the coordinate I entered.
2. When I enter in a coordinate pair, for example 40.0220N 101.9971W, the crosshairs are displayed in the correct location, however, the point graphic that is displayed is not centered on the crosshairs. In this example, 40.0220N 101.9971W, is approximately in the center of the continental US. The crosshairs display at this location, but the point graphic is display off the northwest coast of Venezuela.
NOTE: sometimes the point is centered on the crosshairs.
This might be able to reproduce this by:
- Zooming out to world extent.
- Enter 40.0220N 101.9971W and hit return (the point and crosshairs locations match)
- Now pan to the East so that the center of the US is just on the left edge of map display.
- Now reenter same coordinates, 40.0220N 101.9971W, and hit return. (the crosshairs display at the correct location, but the point displays in Antarctica.

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @jmccausland on December 9, 2016 17:40_

1. Known issue, the "flash" is a tool overlay and only works when tool is active.

2. Usually the point graphic displays incorrectly the first time.  Another known issue, I believe it to be a core issue and there is no workaround ATM.

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @elinz on December 9, 2016 17:54_

If the "flash" only works when the Map Point Tool is active, then I think we have to consider reverting this change so that flash does not work. I think this is going to lead to problems where the user end up capturing incorrect coordinates. 

Thoughts from anybody?

**Comment by lfunkhouser** [comment] 2016-12-14 22:12
_From @elinz on December 13, 2016 22:22_

@kgonzago @jmccausland No response back to my question above.  If the only way to get the "flash" to work in ArcGIS Pro is to make the Map Tool active then we should revert the fix. Having this tool automatically made active is "dangerous". Users will type in a coordinate, hit return, the coordinate is converted, then if they happen to move the mouse over the map display, the output coordinates will automatically update (because the tool was made active without user action) based on the position of the cursor. The user may not notice this and copy the output coordinates which they thought were based on the coordinates they typed in and they would be copying the incorrect coordinates.

**Comment by elinz** [comment] 2016-12-15 23:12
@kgonzago @jmccausland Can we change the code so that after the user hits enter to display the "flash" on the map we disable the Map Point Tool so that the input coordinate stop changing as the user moves the mouse over the map?

**Comment by dhagens** [comment] 2016-12-19 14:34
@jmccausland added a fix for this bug.  @elinz, ready for testing.

**Comment by elinz** [comment] 2016-12-19 17:04
@jmccausland @dhagens I tested in Pro 1.4 with addin built against 1.4 SDK. The flash is working much better and I can see that the Map Point tool is disabled after the flash completes. A couple of things however...
1. After the flash completes at specified location, a second flash occurs to the east of the specified location. In my opinion, a very minor issue.
2. When I explicitly enable the Map Point Tool so I can specify a location using the map, the tool remains enabled for a split second. I enable the tool, move cursor over map and as I'm moving the cursor the tool is disabled. The tool should only be disabled after the user clicks on the map to locate the point. With current behavior there is no way for the user to specify a location of their choosing from the map.

For Coordinate conversion addin, shouldn't all fixes be made to the 1.2 pro branch of the repo, so any fixes will roll forward into the 1.4?

Assigning issue back.

**Comment by dhagens** [comment] 2016-12-19 17:49
@topowright @lfunkhouser, Can one of you make the call on this?  I thought that we were only adding fixes for critical bugs into the 1.2 branch?  This is more of an enhancement and not as much a critical bug.

**Comment by elinz** [comment] 2016-12-19 17:57
@lfunkhouser @dhagens @topowright I asked the question about 1.2, because there is an Asana PBI for "Coordinate Conversion Add-In Bugs Pro 1.2" that states "We are fixing bugs for Coordinate Conversion at the component level (1.2, 1.3, 1.4)...".

**Comment by nfeuerstein** [comment] 2016-12-22 17:36
@dhagens @elinz @lfunkhouser @topowright  Eric Linz was correct, all bug fixes were supposed to be applied at the earliest (if technically possible) version as was outlined in backlog grooming/planning/and the backlog.  Unfortunately, I understand that conflicting guidance was floating around.  We have a tight timeline, so to minimize confusion we will be ONLY focusing on 1.4 at this time (and introducing technical debt in the process as we will eventually need to apply bug fixes for the 1.2/1.3 released versions of these add-ins.  If there is further confusion please let me know.

Is this fixed in 1.4?  If so, can it be verified and closed?

**Comment by dhagens** [comment] 2016-12-22 19:55
This bug was fixed for the 1.3/1.4 branch and is ready for testing.

**Comment by elinz** [comment] 2016-12-22 23:06
@dhagens @nfeuerstein Installed the latest addin built on 1.4 SDK and tested on the latest ArcGIS 1.4 daily build dated 22 Dec 2015 13:27 and the flash is no longer working.

Behavior:
1. With map zoomed out to global extent (topo basemap in map). I enter 34.737N 116.948W (Los Angeles) in the input textbox and hit return. The coordinate is converted, but no flash and point are displayed on the map.

2. With map zoomed in to US, where Los Angeles is not within the current map extent, when I enter 34.737N 116.948W, the map does pan to placed Los Angeles roughly in the middle of map, but does not display a flash and point.

In both cases after I enter the coordinate and hit return, the Map Point tool is enabled and shouldn't be. Not sure if there was a change in the latest build of Pro 1.4 or were the changes made to the addin reverted for some reason.

Assigning back to @dhagens

**Comment by elinz** [comment] 2017-01-04 18:44
@dhagens I tested on latest add-in build dated 04 Jan 2017 09:09.
Entered 45.0N 100.0W.
- The addin does not flash a point or flash the crosshairs. If the entered coordinate does not exist in the current map extent, then the map is centered on the entered coordinate as I would expect.
- The Map Point tool is enabled when I hit enter after enter the coordinates. I would expect the Map Point tool to be disabled after I hit enter and the point/crosshair is flashed.

**Comment by dhagens** [comment] 2017-01-04 19:11
@elinz, was this in the Pro or ArcMap addin?
@jmhauck Do you want to take a look at this since you are working on Coordinate Conversion?  @jmccausland added this functionality for the Pro addin I believe.  Maybe it just wasn't added to the ArcMap addin or vice versa.

**Comment by jmhauck** [comment] 2017-01-04 19:21
@dhagens I will take a look

**Comment by elinz** [comment] 2017-01-04 20:29
@dhagens @jmhauck @jmccausland This issue is with Pro.

**Comment by dfoll** [comment] 2017-01-05 19:07
documentation is affected by this because it currently mentions the flash upon pressing enter, this will need changed with the issue is not fixed for this release

**Comment by elinz** [comment] 2017-01-10 04:02
@jmhauck Installed Pro addin build 09 Jan 2017 16:49 on ArcGIS Pro 1.4 final build and this is still not working.

**Comment by topowright** [comment] 2017-01-10 18:57
@lfunkhouser @nfeuerstein @kgonzago @elinz I have looked into this a bit further and I can verify that the fix that @jmhauck made works in the single component add-in, but not in the single Military Tools Add-in. This tells me that this is just a sync issue with Jenkins. @kgonzago please let me know if I can be of any help.

**Closed** 2017-01-11 21:15 UTC
Labels: 0 - Backlog, B - Affects Documentation, B - Bug, priority - normal
