### ISSUE TITLE
Support Dark Theme within the Ambigous Coordinate dialog

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#490] opened 2018-04-20 12:36 UTC
### Ambiguous Coordinate dialog 
![image](https://user-images.githubusercontent.com/5488313/39051145-6cea8780-446d-11e8-8e52-2d3441019562.png)

### Expected Results
The expected results are full support for dark theme for both the import and export dialogues. They would be similar to this:

![image](https://user-images.githubusercontent.com/5488313/39051166-7f3f46c8-446d-11e8-9990-d1a9d994a34f.png)

**Comment by topowright** [comment] 2018-05-01 15:48
@CTLocalGovTeam the way forward that you shared on this issue has been approved by @lfunkhouser. Can you please provide detailed comments in the code on where we are duplicating the code to support Dark Theme in ArcGIS Pro and ArcMap

**Comment by dfoll** [comment] 2018-08-06 16:39
put the high priority label on this issue because @topowright and I noticed behavior that after closing the ambiguous coordinates window  in dark theme, ArcGIS Pro crashes. Related to this comment we noticed that occasionally (but not yet consistently reproducible, the ambiguous coordinates window will pop up behind ArcGIS Pro, appearing at first as though ArcGIS Pro is frozen, because it is waiting for you to dismiss the window before you click anything else)

**Closed** 2018-09-10 18:31 UTC
Labels: A-bug, B-high, CT-Fixed, CyberTech, E-verified, V -  Pro 2.1, V - MT 3.2
