### ISSUE TITLE
Manual inputs are not added to the Batch Conversion List

### ISSUE THREAD

**Issue by adgiles** [Esri/coordinate-conversion-addin-dotnet#404] opened 2017-06-26 08:24 UTC
If you manually enter coordinates through the input field they do not get added to the list. I would expect the list to behave the same way for manual entry as it does for Map Point Tool.

**Comment by NatalieCampos** [comment] 2017-09-07 15:44
Additionally, if coordinates are pasted into the input field the do not apear in the List.  This was tested in ArcMap 10.3.1

**Comment by dfoll** [comment] 2017-09-07 16:10
edited the issue title, for clarification, manual entry could be either typing, or copy/paste

**Comment by lfunkhouser** [comment] 2018-05-16 01:08
Closing. This is a duplicate of #457.

**Closed by lfunkhouser** 2018-05-16 01:08 UTC
Labels: A-bug, B-high, E-duplicate, V - 10.3.1, V - Pro 1.4
