### ISSUE TITLE
Support for custom DMS format of DD-MM-SS.SS

### ISSUE THREAD

**Issue by topowright** [Esri/coordinate-conversion-addin-dotnet#468] opened 2018-01-26 07:12 UTC
Support FAA format by creating a custom configuration
#### Background
Supporting this format thru the use of our configuration options of a DMS coordinate will allow this addin to support the FAA format. 

https://community.esri.com/thread/207791-faa-oeaaa-latitudelongitude-coordinates

#### Current State
**Input**
![image](https://user-images.githubusercontent.com/5488313/44541927-54b6d500-a6c0-11e8-8c59-d56d2cd11995.png)

**Output**
![image](https://user-images.githubusercontent.com/5488313/44541904-3f41ab00-a6c0-11e8-9275-191f98703dae.png)

#### Expected behavior
All coordinate types should accept all characters to allow users to configure the output format. This can be tested on DDM and DMS which currently are not supporting dashed (-) symbols.

**Comment by lfunkhouser** [comment] 2018-02-14 14:10
@karlterrey Can you follow up with this user on GeoNet if possible to gather any requirements for this format?

**Comment by karlterrey** [comment] 2018-02-14 15:06
Will do

**Comment by karlterrey** [comment] 2018-02-23 20:55
Customer feedback from Hannah Shepherd at Apex Clean Energy, in VA. hannah.shepherd@apexcleanenergy.com  

The FAA has a mandated protocol for locations that are electronically filed with them. 
Hannah’s organization is a wind developer and files locations of facilities with the FAA using the FAA’s OEAAA E-Filing system. Specifically they have issues with the DMS format needing to be in DD-MM-SS.SS for Lat and Lon of each facilities location. This can sometimes be in batches of 150 – 200. 

A second important factor in their workflow is the elevation at each specific point. ESRI’s Extract Values to Points tool helps with that currently. 

This would help in reinforcing that our work is non ITAR
[_FAA_Template for coord conversion.xlsx](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/1753122/_FAA_Template.for.coord.conversion.xlsx)

**Comment by topowright** [comment] 2018-08-06 16:52
This should be able to be done by configuring the DDM output.

**Comment by topowright** [comment] 2018-08-23 17:37
@saip please let me know if the updated content in the issue description clarifies the requirments.

**Comment by lfunkhouser** [comment] 2018-10-10 14:27
added CT-fixed label since it was developed/delivered in #518. 
added working labels for testing and doc

**Comment by dfoll** [comment] 2018-10-30 14:07
Recently rebuilt CC build 19 and MT build 122 to test

**Comment by BobBooth** [comment] 2018-11-01 17:19
MGRS and USNG are not supporting dashes, or other special characters in Pro 2.3.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/b53e3e7e-744d-45a1-8e36-b1fa6676098c)

**Comment by kgonzago** [comment] 2018-11-06 18:40
Using MT build 126, I confirmed FAA format for custom DMS notation is supported.

I also confirmed, as [reported](https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/468#issuecomment-435115865) by @BobBooth, the add-in does not support dashes for MGRS and USNG notations.

**Comment by kgonzago** [comment] 2018-11-07 19:00
Added new [test](https://github.com/ArcGIS/solutions-defense-test-catalog/pull/176) for checklist

**Comment by dfoll** [comment] 2018-11-09 18:13
This issue represents a subset of cases for #347 and #348. This is is satisfied given the initial issue. A new issue needs to be logged as a response to this, as this issue does not account for Northern/Southern or Eastern/Western hemisphere coordinates.
![image](https://user-images.githubusercontent.com/5322669/48280338-4b1c4e00-e421-11e8-833e-bcdc7629d92a.png)

**Comment by dfoll** [comment] 2018-11-09 18:38
#542 was opened to clarify the proper formatting for FAA coordinates.

**Comment by lfunkhouser** [comment] 2018-11-12 16:07
@dfoll if the coordinates are not in the proper location, this issue has not been delivered. Reassigning to @CTLocalGovTeam . @saip please work with @dfoll for the guidance.

**Comment by dfoll** [comment] 2018-11-12 16:22
@lfunkhouser we need to find time to understand this format better, or have connected with someone who already does before any meaningful work can be done

**Comment by lfunkhouser** [comment] 2018-11-29 18:45
Support for custom FAA format by using the map point tool was delivered. Issue #542 will need to be addressed in a future release to support the input/importing of FAA coordinates.

**Comment by csmoore** [comment] 2019-06-14 10:41
This issue was reintroduced with fix for #527, https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/527#issuecomment-494955592 PRs #602 , #612 that disallowed "+/-" in formatting - Reopening.

**Comment by dfoll** [comment] 2019-06-18 11:55
Proposed fix for this is to improve the parsing logic that was put into place to fix issue #527. Details of proposed improvement listed in #527

**Comment by dfoll** [comment] 2019-06-24 19:07
CC build 145 brought back the ability to use a "-" as a separator between `DD-MM` or `MM-SS.SS` when creating custom formatting . A "-" in front of the DD is not allowed to be used when creating custom formatting. When using custom formatting the "-" will still be placed for S and W hemisphere if the "Show - for S/W hemisphere" check box is marked. See #600 for more details.

**Comment by dfoll** [comment] 2019-06-24 23:41
- https://solutionsdev.arcgis.com/defense/what-is-new/ (pending [this pr](https://github.com/ArcGIS/arcgis-solutions-website/pull/7914))
- https://solutionsdev.arcgis.com/defense/help/coordinate-conversion/resources/june-2019-coordinate-conversion.htm
- \\...\CoordinateConversion\Dev\148\
-
-

**Comment by lfunkhouser** [comment] 2019-06-26 02:05
verified what's new and release notes on solutionsdev, pdfs in CC build 148 and MT 316

**Comment by dfoll** [comment] 2019-06-26 12:02
i thought about this. the reason i put new labels on it and listed it again is in case a user has or does encounter with like 3.4

**Comment by lfunkhouser** [comment] 2019-06-27 13:00
verified doc on MT 317, CC 154, and 3 topics on solutionsstg.

**Closed by lfunkhouser** 2019-06-27 13:00 UTC
Labels: A-feature, CT-Fixed, CyberTech, E-verified, G-QC (Doc), V - 10.4.1, V - MT 3.5, V - Pro 2.4
