### ISSUE TITLE
BUG-000102904 ArcMap crashes when changing display coordinates after using Map Point Tool

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/coordinate-conversion-addin-dotnet#319] opened 2017-03-10 18:34 UTC
The Coordinate Conversion tool of Military Tools for ArcGIS crashes ArcMap when changing the display coordinates after using the Map Point Tool.

Steps to Repro:

1. Open a blank map with no coordinate system assigned to the data frame (this was tested in both 10.3.1 and 10.4.1.  Crash occurred consistently with these steps).
2. Open the Coordinate Conversion pane by clicking the Coordinate Conversion button from the Military Tools toolbar.
3. Click the Edit Properties icon.  This opens the Display Coordinate dialog.  The dialog opens with a default display coordinate of DD.
4. Use the dropdown to select another display coordinate.  No crash.
5. Click the Map Point tool.
6. Click around in the blank map.  Nothing happens yet, and nothing shows up in the Input box of the Convert pane.
7. Click Edit Properties again and change the display coordinates.
8. ArcMap crashes.

Product: ArcGIS for Desktop Team: Solution Templates
Functional Area: ArcGIS for Defense Description: Military Tools for ArcGIS
Client Platform: Version Found: 10.3.1

Attachment: screenshots
[a3Y39000000T8KGEA0~1~ConvertCoordinates_crash.docx](https://github.com/Esri/coordinate-conversion-addin-dotnet/files/834805/a3Y39000000T8KGEA0.1.ConvertCoordinates_crash.docx)

**Comment by kgonzago** [comment] 2017-05-01 21:48
@lfunkhouser Enabling the map tool and clicking in map without an existing basemap or feature layer will cause it to crash. The fix is to perform a check on spatial reference of the map before the map tool can be enabled. Will update code to include that check.

**Comment by kgonzago** [comment] 2017-05-02 17:03
@lfunkhouser Please have one of PEs verify. Thanks.

**Comment by kgonzago** [comment] 2017-05-02 18:23
@ACueva @NatalieCampos @topowright @dfoll FYI

**Comment by topowright** [comment] 2017-05-03 00:07
@kgonzago I have replicated this issue.

**Comment by topowright** [comment] 2017-05-03 00:11
I am testing this issue on build 05-02-2017_1422 to see if this is fixed

**Comment by topowright** [comment] 2017-05-03 00:26
On build 1422 and I see a few issues.
If I add a spatial reference and then try to add a coordinate from the map using the map point tool it will not update the coordinates in the add-in. If I change the coordinates again I then get this error: 

![image](https://cloud.githubusercontent.com/assets/5488313/25644596/4ad41566-2f5c-11e7-9cc3-fef67845fb73.png)

The dialog to change coordinates is now buried behind ArcMap. Once I try to close this ArcMap crashes.

**Comment by kgonzago** [comment] 2017-05-03 13:21
@topowright I'll take a look at it

**Comment by topowright** [comment] 2017-05-03 16:25
@kgonzago after we spoke this morning I was thinking more about the thought of the tool working with a blank dataframe. I agree with you that we dont want the tool to crash; however, how would we go about that?

**Comment by kgonzago** [comment] 2017-05-03 20:17
@topowright @ACueva @NatalieCampos Changes made to map tool. now a map is required before the map tool can be enabled. Please verify when you get a chance.

**Comment by ACueva** [comment] 2017-05-03 21:15
If this is the expected result, it appears to be working. 
![2017-05-03_14-12-34](https://cloud.githubusercontent.com/assets/3093940/25681823/98c3860e-300a-11e7-83b6-96fac0ec9373.png)

@kgonzago I'm going to assume this is the behavior you added.  If it's not please let us know.

**Comment by ACueva** [comment] 2017-05-03 21:16
@topowright @NatalieCampos - This has an "affects documentation", does it?

**Comment by topowright** [comment] 2017-05-03 23:37
@kgonzago this looks good.

**Comment by kgonzago** [comment] 2017-05-04 13:12
@topowright Displaying that message is now the intended behavior. Map has to exist before the map tool is enabled.

@ACueva Adding this new behavior unfortunately does affect documentation.

**Comment by topowright** [comment] 2017-05-04 18:54
@ACueva I think this needs to be documented in the known issues. This is my idea of what we should say. 

When creating a new mxd in ArcMap the map point tool for coordinate conversion will not work without a user adding a layer to the Table of Contents if a user has previously used the map point tool in the previous ArcMap mxd. Add a layer to the Table of Contents and the map point tool will work. 

Please let me know if you agree.

**Comment by ACueva** [comment] 2017-05-04 19:08
@topowright I think it's a bit convoluted.

Let's wait to see in planning whether or not this can/will be fixed before the next release.  Perhaps this is a non issue if we can get it fixed.

**Comment by kgonzago** [comment] 2017-05-15 20:10
@ACueva @topowright can this be closed?

**Comment by ACueva** [comment] 2017-05-15 20:45
@kgonzago I'll update the documentation and close this.

**Comment by kgonzago** [comment] 2017-05-16 12:59
@ACueva Thank you.

**Comment by ACueva** [comment] 2017-05-16 17:59
@kgonzago Build 1474, this is happening:
![2017-05-16_10-58-19](https://cloud.githubusercontent.com/assets/3093940/26120757/aed3205a-3a26-11e7-88a4-431a68be4a13.png)

**Comment by kgonzago** [comment] 2017-05-16 18:00
@ACueva Can you provide detailed steps to repro? Thanks.

**Comment by ACueva** [comment] 2017-05-16 18:03
@kgonzago I used the steps listed in the initial bug.

**Comment by kgonzago** [comment] 2017-05-16 19:45
@ACueva This issue will be fixed with PR #344

**Comment by ACueva** [comment] 2017-05-16 20:32
Looks like the PR was merged.  Kicking off a new build and re-testing.

**Comment by ACueva** [comment] 2017-05-16 21:13
@kgonzago Changes look good.  I get the warning message if a basemap/layer isn't present(as expected). 

I tried the previous workflow @topowright mentioned.  I can consistently get an error message whenever a basemap/layer isn't present.  I tried removing the layer/basemap after successfully running the map point tool.  Still throws the error (good).

At this point I don't believe there is a need to document this as a known issue as the behavior is working as expected.

Not closing quite yet as I need to clarify a few documentation things offline with @lfunkhouser.

**Comment by ACueva** [comment] 2017-05-17 23:27
Moving to "In progress" as I'll be updating our documentation.

**Comment by topowright** [comment] 2017-05-24 14:31
@ACueva @kgonzago found an issue in which ArcMap is not treating raw elevation data as a item and the tool thinks that there is no data in the ToC: 
![image](https://cloud.githubusercontent.com/assets/5488313/26408552/f73a99a4-4052-11e7-89be-9f3943c93e83.png)

**Comment by NatalieCampos** [comment] 2017-05-25 21:04
Closing issue.  @lfunkhouser 's original issue has been fixed.  I also do not see the issue with the raw elevation data as seen by @topowright

**Closed by NatalieCampos** 2017-05-25 21:04 UTC
Labels: 3 - Verify, B - Affects Documentation, B - Bug, effort-extra small, support, V - 10.3.1

**Comment by NatalieCampos** [comment] 2017-05-25 21:36
The following was added to the Known Issues for CC in ArcMap documentation

> The map point tool for Coordinate Conversion will not active until a layer is added to the Table of Contents.
